name: Release

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup PNPM
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to Visual Studio Marketplace
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registry: vs-marketplace
          debug: true
          dry-run: false

      - name: Publish to Visual Studio Marketplace (File)
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registry: vs-marketplace
          debug: true
          dry-run: true
          extension-path: test-vscode-extension-0.0.4.vsix
          targets: "win32-x64, linux-x64, linux-arm64, darwin-x64, darwin-arm64"

      - name: Publish to Open VSX
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.OPENVSX_MARKETPLACE_TOKEN }}
          registry: open-vsx
          debug: true
          dry-run: false

      - name: Publish to Open VSX (File)
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.OPENVSX_MARKETPLACE_TOKEN }}
          registry: open-vsx
          debug: true
          dry-run: true
          extension-path: test-vscode-extension-0.0.4.vsix
          targets: "win32-x64, linux-x64, linux-arm64, darwin-x64, darwin-arm64"
