name: Release

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to Open VSX Registry
        uses: luxass/publish-vscode-extension@v1
        with:
          token: ${{ secrets.OPEN_VSX_TOKEN }}
          registry: open-vsx

      - name: Publish to Visual Studio Marketplace
        uses: luxass/publish-vscode-extension@v1
        with:
          token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registry: vs-marketplace
