name: Release

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup PNPM
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to Visual Studio Marketplace
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registry: vs-marketplace
          debug: true
          dry-run: false

      - name: Publish to Visual Studio Marketplace (File)
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registry: vs-marketplace
          debug: true
          dry-run: true
          extension-path: test-vscode-extension-0.0.4.vsix
          targets: "win32-x64, linux-x64, linux-arm64, darwin-x64, darwin-arm64"

      - name: Publish to Open VSX
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.OPENVSX_MARKETPLACE_TOKEN }}
          registry: open-vsx
          debug: true
          dry-run: false

      - name: Publish to Open VSX (File)
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.OPENVSX_MARKETPLACE_TOKEN }}
          registry: open-vsx
          debug: true
          dry-run: true
          extension-path: test-vscode-extension-0.0.4.vsix
          targets: "win32-x64, linux-x64, linux-arm64, darwin-x64, darwin-arm64"
