name: Release

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Setup PNPM
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to Visual Studio Marketplace
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registry: vs-marketplace
          debug: true
          dry-run: false

      - name: Publish to Visual Studio Marketplace (File)
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registry: vs-marketplace
          debug: true
          dry-run: true
          extensionPath: test-vscode-extension-0.0.4.vsix
          target: vs-marketplace, vs-marketplace-staging

      - name: Publish to Open VSX
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.OPENVSX_MARKETPLACE_TOKEN }}
          registry: open-vsx
          debug: true
          dry-run: false

      - name: Publish to Open VSX (File)
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.OPENVSX_MARKETPLACE_TOKEN }}
          registry: open-vsx
          debug: true
          dry-run: true
          extensionPath: test-vscode-extension-0.0.4.vsix
          target: |
            - open-vsx
            - open-vsx-staging
