name: Release

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup PNPM
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to Open VSX Registry
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.OPEN_VSX_TOKEN }}
          registry: open-vsx

      - name: Publish to Visual Studio Marketplace
        uses: luxass/publish-vscode-extension@main
        with:
          token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registry: vs-marketplace
